name: Build User Service

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
  push:

permissions:
  security-events: write
  pull-requests: read
  contents: read

jobs:
  call-service-workflow:
    uses: wander-suite/wander-devops/.github/workflows/service-workflow.yml@main
